version: '3'
services:
  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    ports: 
      - 3306:3306

  # WordPress Service
  wordpress:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
    container_name: wp_container
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./wp_data:/var/www/html
      - ./docker/wordpress/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/wordpress/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      WORDPRESS_DB_HOST: mysql_container
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      XDEBUG_SESSION: 1

    ports:
      - "8000:80"

volumes:
  db_data:
